# workflow level env vars cannot be used at the job level
# https://github.community/t/how-to-set-and-access-a-workflow-variable/17335/15
name: Periodic workflow test
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
jobs:
  setup:
    name: Setup cache
    uses: simleo/sars-cov-2-se-illumina-wgs-variant-calling/.github/workflows/setup.yml@main
    with:
      python-version-list: "[\"3.7\"]"
      galaxy-fork: galaxyproject
      galaxy-branch: master
  test:
    name: Test workflow
    needs: setup
    uses: simleo/sars-cov-2-se-illumina-wgs-variant-calling/.github/workflows/test_workflows.yml@main
    with:
      galaxy-head-sha: ${{ needs.setup.outputs.galaxy-head-sha }}
      python-version-list: "[\"3.7\"]"
      galaxy-fork: galaxyproject
      galaxy-branch: master
      repository-list: '.'
      check-outputs: true
